name: hetima
version: 0.0.026
author: kyorohiro
description: A pub package
homepage: https://github.com/kyorohiro/dart_hetimalib
dependencies:
  chrome: any
  chrome_ext: any
  crypto: any
  unittest: any
  xml: any
